name: CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build

      - name: Set up Git
        run: |
          git config --global user.email "mrezaie264@gmail.com"
          git config --global user.name "Mohammad Rezaie"
          git config --global credential.helper store

      - name: Deploy to GitHub Pages
        run: |
          npm run deploy
          git config --global user.email "mrezaie264@gmail.com"
          git config --global user.name "Mohammad Rezaie"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}